# Generated by Django 6.0.5 on 2026-05-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_test_case', to='defects.defect')),
            ],
        ),
    ]
